version: '3'

tasks:
  clone-pgv:
    desc: build protoc-gen-validate
    cmds:
      - '[ ! -d vendor/protoc-gen-validate ] && git clone --depth 1 https://github.com/bufbuild/protoc-gen-validate.git vendor/protoc-gen-validate || echo "vendor/protoc-gen-validate already exists, skipping clone"'
      - make -C vendor/protoc-gen-validate build

  generate-proto-dto:
    desc: dto proto generate
    cmds:
      - mkdir -p gen/
      - |
        protoc \
          -I. \
          -I=vendor/protoc-gen-validate \
          --go_out=gen/ \
          --go_opt=paths=source_relative \
          --go-grpc_out=gen/ \
          --go-grpc_opt=paths=source_relative \
          --validate_out=lang=go,paths=source_relative:gen \
          proto/dto/base_station.proto \
          proto/dto/rover.proto \
          proto/dto/enums.proto

  generate-proto-api:
    desc: api proto generate
    cmds:
      - mkdir -p gen/
      - |
        protoc \
          -I. \
          -I=vendor/protoc-gen-validate \
          --go_out=gen/ \
          --go_opt=paths=source_relative \
          --go-grpc_out=gen/ \
          --go-grpc_opt=paths=source_relative \
          proto/api/base_station_v1/base_station.proto \
          proto/api/rover_v1/rover.proto \
          proto/api/coord_correction_v1/coord_correction.proto

  clean-vendor:
    desc: delete temporary folder vendor
    cmds:
      - rm -rf vendor

  clean-gen:
    desc: deleting old version of files
    cmds:
      - rm -rf gen

  generate-proto:
    desc: full protobuf generation
    cmds:
      - task: clean-gen
      - task: clone-pgv
      - task: generate-proto-dto
      - task: generate-proto-api