version: '3'

tasks:
  generate-proto:
    desc: Генерация Go-кода из .proto файлов
    cmds:
      - |
        mkdir -p gen/
        protoc \
          -I.  \
          --go_out=gen/ \
          --go_opt=paths=source_relative \
          --go-grpc_out=gen/ \
          --go-grpc_opt=paths=source_relative \
          proto/api/base_station_v1/base_station.proto \
          proto/api/rover_v1/rover.proto \
          proto/api/coord_correction_v1/coord_correction.proto \
          proto/dto/base_station.proto \
          proto/dto/rover.proto \
